### ISSUE TITLE
applicationUrl  이 더 이상 유효 하지 않은거 같습니다.

### ISSUE THREAD

**Issue by Dharmogata** [visvaden7/PatentAI#1]
http://plus.kipris.or.kr/kipo-api/kipi/patUtiModInfoSearchSevice/getBibliographyDetailInfoSearch?applicationNumber={inputNumber}&ServiceKey={KIPRIS_API_KEY}

상기 URL를 현재는 키프리스 플러스에서 API 로 제공 하지 않는 거 같습니다. 키프리스에 유선 문의하니 공공데이터 포털에서 제공하는 URL이라고 하는데 공공데이터 포털을 뒤져봐도 찾을 수 없었습니다. 어디서 상기 URL을 찾을 수 있는지 문의 드립니다. 

참고로 코드를 실행하니      resultMsg>서비스 이용 권한(기간)이 만료되었거나, 입력하신 서비스키 값이 잘못 되었습니다.[4]</resultMsg>  라고 fail 한 결과값이 뜨네요.

**Comment by visvaden7** [comment]
@Dharmogata 
kipris plus 사이트에서 데이터 서비스(메뉴) -> OpenAPI -> 특허실용공개*등록정보 에서 들어가시면 찾아보실 수 있습니다.
회원가입 후 사용가능하세요~

https://plus.kipris.or.kr/portal/popup/service/DBII_000000000000001/view.do
